version: '3'
services:
  portainer:
    image: portainer/portainer-ce:2.21.3
    container_name: portainer
    restart: always
    ports:
      #- "8000:8000"   # port HTTP
      - "9443:9443"   # port HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - portainer_data:/data  
volumes:
  portainer_data:
